language: python

python:
 - pypy
 - pypy3
 - 2.6
 - 2.7
 - 3.2
 - 3.3
 - 3.4
 - 3.5

# Use container-based infrastructure
sudo: false

install:
 - pip install pillow
 - pip install coverage
 - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip install unittest2; fi

script:
 - coverage run --source=EXIF ./test.py -v

after_success:
 - pip install coveralls
 - coveralls

after_script:
 - coverage report
 - pip install pep8 pyflakes
 - pep8 --statistics --count *.py
 - pyflakes *.py | tee >(wc -l)

matrix:
  fast_finish: true
